name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Продолжать сборку других целей при ошибке
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: mango-launcher
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: mango-launcher.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            binary: mango-launcher.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: mango-launcher
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: mango-launcher

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build binary
      run: cargo build --verbose --release --target ${{ matrix.target }}

    - name: Prepare artifact
      shell: bash
      run: |
        mkdir -p artifact
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "target/${{ matrix.target }}/release/${{ matrix.binary }}" "artifact/mango-launcher-${{ matrix.target }}.exe"
        else
          cp "target/${{ matrix.target }}/release/${{ matrix.binary }}" "artifact/mango-launcher-${{ matrix.target }}"
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.target }}
        path: artifact/*
        if-no-files-found: error

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: ${{ contains(github.ref, '-pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 